---
# tasks file
# tasks follow:
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_file_systems/deploying-an-nfs-server_managing-file-systems

- name: Install the nfs-utils package
  ansible.builtin.dnf:
    name: nfs-utils
    state: present

- name: Edit the /etc/nfs.conf file
  ansible.builtin.copy:
    src: nfs-v4-only.conf
    dest: /etc/nfs.conf
    owner: root
    group: root
    mode: '0644'

# systemctl mask --now rpc-statd.service rpcbind.service rpcbind.socket
- name: Disable all NFSv3-related services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: false
    masked: true
  loop:
    - rpc-statd.service
    - rpcbind.service
    - rpcbind.socket

- name: Create a directory that you want to share
  ansible.builtin.file:
    path: "{{ item.directory }}"
    state: directory
    mode: '2770'
    group: "{{ item.group }}"
    setype: "{{ item.selinux_file_context_type }}"
    # recurse: true
  loop: "{{ directories_to_export }}"

- name: Add an export point to the /etc/exports file for each directory
  ansible.builtin.lineinfile:
    path: /etc/exports.d/pulp.exports
    line: "{{ item.directory }}  {{ item.nfs_options }}"
    create: true
    owner: root
    group: root
    mode: '0644'
  loop: "{{ directories_to_export }}"
  notify: Apply changes to the exports file

- name: Open the relevant ports in firewalld
  ansible.posix.firewalld:
    service: nfs
    permanent: true
    state: enabled
    immediate: true

- name: Verify that the server provides only the NFS versions that you have configured
  ansible.builtin.debug:
    msg: "cat /proc/fs/nfsd/versions: {{ lookup('ansible.builtin.file', '/proc/fs/nfsd/versions') }}"
