# local key pair
#
- name: Add ansible's private key to the control node
  ansible.builtin.copy:
    content: "{{ control_node_private_key }}"
    dest: "{{ control_node_private_key_file }}"
    mode: '0600'
  delegate_to: localhost
  connection: local
  become: no

# occasionally useful to keep a local copy of the pubkey 
- name: Also store the public key on the control node
  ansible.builtin.copy:
    content: "{{ managed_node_public_key }}"
    dest: "{{ control_node_public_key_file }}"
    mode: '0644'
  delegate_to: localhost
  connection: local
  become: no


