---
# tasks file

- name: Install required packages
  ansible.builtin.yum:
    name: cockpit
    state: present

- name: Start the sysadmin console 'cockpit' if a request comes in
  ansible.builtin.systemd_service:
    name: cockpit.socket
    state: started
    enabled: true
