---
# tasks file
# reference
#  How to apply a system wide proxy?
# https://access.redhat.com/solutions/1351253

- name: Add lines to the environment file
  ansible.builtin.blockinfile:
    path: /etc/environment
    block: |
      http_proxy=http://{{ proxy_server }}:3128
      HTTPS_PROXY=http://{{ proxy_server }}:3128
      no_proxy=localhost,127.0.0.1,example.com

# !!! add this?
# /etc/profile.d/http_proxy.sh
