---
# tasks file

# reference
# https://access.redhat.com/articles/rhc
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/automating_system_administration_by_using_rhel_system_roles/using-the-rhc-system-role-to-register-the-system_automating-system-administration-by-using-rhel-system-roles
# packages
# rhc                  connects the system to Red Hat hosted services
# rhc-worker-playbook  is a Python worker for Red Hat connector that launches Ansible Runner

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - rhc
      - rhc-worker-playbook
    state: present

- ansible.builtin.include_role:
    name: redhat.rhel_system_roles.rhc
  vars:
    rhc_auth:
      login:
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
    rhc_proxy:
      hostname: "{{ server_proxy_hostname }}"
      port: "{{ server_proxy_port }}"
