---
# https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html

- name: "Use gateway {{ lab_net_prefix }}.3 as the DNS server"
  community.general.nmcli:
    conn_name: enp1s0
    type: ethernet
    dns4:
      - "{{ lab_net_prefix }}.3"
    state: present

- name: Brings up the interface to load change
  ansible.builtin.command: 
    cmd: "nmcli con up {{ nic_name }}"
  register: r_up
- name: Display result
  ansible.builtin.debug:
    var: r_up
