---
# defaults file

directories_to_export:
  - directory: /nfs/projects/pulp
    group: pulp
    selinux_file_context_type: nfs_t
    nfs_options: '(rw,no_root_squash)'
  - directory: /nfs/projects/pulpcore_static
    group: pulp
    selinux_file_context_type: var_lib_t
    nfs_options: '(rw,no_root_squash)'
