---
# make sure the new machine has been rebooted before upgrading all packages
# If kickstart failed to register with RHSM, this module does nothing.
- name: Upgrade all packages
  ansible.builtin.yum:
    name: "*"
    state: latest
  register: r_yum

- name: Display
  ansible.builtin.debug:
    var: r_yum

- name: Can the OS survive another reboot?
  ansible.builtin.reboot:
  when: r_yum['changed']

- name: "Can we ping {{ inventory_hostname }} after the reboot?"
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 30
  delegate_to: "{{ inventory_hostname }}"
